/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Livez
         * @description Process is up. Deliberately touches no dependency.
         */
        get: operations["livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Could this instance take a meeting right now? (tech spec 15.)
         *
         *     503 when not, with the reason in the body — a load balancer needs the
         *     status code, and the person reading the logs afterwards needs the sentence.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/deps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Deps
         * @description Per-dependency detail. Always 200 — this endpoint reports, it does not judge.
         *
         *     Separate from `/readyz` because they are read by different things: a load
         *     balancer wants a status code, and a person wants to know which of three
         *     dependencies is the one that is broken.
         */
        get: operations["health_deps_health_deps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Meetings
         * @description Meetings for the caller's organization, newest first.
         */
        get: operations["list_meetings_meetings_get"];
        put?: never;
        /**
         * Create Meeting
         * @description Create a meeting and return the host token plus the invite link.
         */
        post: operations["create_meeting_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meeting */
        get: operations["get_meeting_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Meeting
         * @description Exchange an invite token for a session token (tech spec 13.1).
         *
         *     The only unauthenticated route. The invite token is compared against its
         *     stored hash; it is never held in plain text on the server.
         */
        post: operations["join_meeting_meetings__meeting_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End Meeting
         * @description End a meeting (tech spec 11). Idempotent: calling it twice is a no-op.
         *
         *     Ordering matters. The drain runs to a durable boundary *before* the meeting
         *     is marked COMPLETED, so a crash mid-finalization leaves FINALIZING for the
         *     startup recovery routine rather than a COMPLETED meeting missing segments.
         */
        post: operations["end_meeting_meetings__meeting_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transcript
         * @description Final segments in display order. Interim text is never stored (ADR-05).
         *
         *     `?q=` filters to segments containing the text (FR-10, tech spec §6). The
         *     match is accent-insensitive — see `transcript/search.py` for why that is
         *     worth a deviation from the spec's "ILIKE for now" in a French-first product.
         *
         *     Filtering happens after the fetch, which costs nothing extra: rendering the
         *     transcript already loads every segment.
         */
        get: operations["get_transcript_meetings__meeting_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Outputs
         * @description Outputs when they exist, otherwise 202 with the job's state.
         */
        get: operations["get_outputs_meetings__meeting_id__outputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/audio/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audio
         * @description Stored PCM for one audio session, with Range support (tech spec 6, FR-11).
         *
         *     The review page seeks by timestamp, and `store.py` makes that arithmetic
         *     rather than a lookup: the file holds silence padding too, so
         *     `byte_offset = session_ms * BYTES_PER_MS` is exact. This route does not
         *     need to know that — it answers in bytes and lets the caller do the sum.
         *
         *     Tenancy is enforced the same way every other read is, and then once more:
         *     the `AudioSession` row must belong to the meeting named in the path, so a
         *     valid session id from another meeting in the same organization cannot be
         *     replayed here.
         */
        get: operations["get_audio_meetings__meeting_id__audio__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemView */
        ActionItemView: {
            /** Text */
            text: string;
            /** Evidence Segment Ids */
            evidence_segment_ids: string[];
            /** Owner Participant Id */
            owner_participant_id?: string | null;
            /** Owner Text */
            owner_text?: string | null;
            /** Due Text */
            due_text?: string | null;
        };
        /**
         * AudioSessionView
         * @description Where one participant's recording sits on the meeting timeline.
         *
         *     The review page needs `epoch_ms` to turn a segment's meeting-relative
         *     `start_ms` into an offset inside the file:
         *
         *         offset_ms = segment.start_ms - session.epoch_ms
         *
         *     Sent alongside the segments rather than repeated on each one, because it is
         *     a property of the recording and there are a handful of recordings and
         *     hundreds of segments.
         */
        AudioSessionView: {
            /** Id */
            id: string;
            /** Participant Id */
            participant_id: string;
            /** Epoch Ms */
            epoch_ms: number;
        };
        /** CreateMeetingRequest */
        CreateMeetingRequest: {
            /** Title */
            title: string;
        };
        /** CreateMeetingResponse */
        CreateMeetingResponse: {
            meeting: components["schemas"]["MeetingView"];
            /** Host Token */
            host_token: string;
            /** Invite Url */
            invite_url: string;
        };
        /**
         * DependencyView
         * @description One dependency's state (tech spec 15, `/health/deps`).
         */
        DependencyView: {
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Detail */
            detail: string;
            /** Gates Readiness */
            gates_readiness: boolean;
        };
        /** EndMeetingResponse */
        EndMeetingResponse: {
            meeting: components["schemas"]["MeetingView"];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /**
         * ErrorEnvelope
         * @description Every failure response uses this shape (tech spec 6).
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Text */
            text: string;
            /** Evidence Segment Ids */
            evidence_segment_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** JoinRequest */
        JoinRequest: {
            /** Display Name */
            display_name: string;
            /** Invite Token */
            invite_token: string;
        };
        /** JoinResponse */
        JoinResponse: {
            participant: components["schemas"]["ParticipantView"];
            /** Session Token */
            session_token: string;
            /** Ws Url */
            ws_url: string;
            meeting: components["schemas"]["MeetingView"];
        };
        /** MeetingDetailView */
        MeetingDetailView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Language */
            language: string;
            /** Source Kind */
            source_kind: string;
            /** Transcript Version */
            transcript_version: number | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Participants */
            participants?: components["schemas"]["ParticipantView"][];
        };
        /** MeetingListResponse */
        MeetingListResponse: {
            /** Meetings */
            meetings: components["schemas"]["MeetingView"][];
        };
        /** MeetingView */
        MeetingView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Language */
            language: string;
            /** Source Kind */
            source_kind: string;
            /** Transcript Version */
            transcript_version: number | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OutputsResponse
         * @description 202 while the job is pending; the body's `status` says which (X-12).
         */
        OutputsResponse: {
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
            /** Key Points */
            key_points?: string[];
            /** Decisions */
            decisions?: components["schemas"]["EvidenceItem"][];
            /** Action Items */
            action_items?: components["schemas"]["ActionItemView"][];
            /** Open Questions */
            open_questions?: components["schemas"]["EvidenceItem"][];
            /** Error Code */
            error_code?: string | null;
        };
        /** ParticipantView */
        ParticipantView: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Summary */
            summary: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyView"][];
        };
        /**
         * SegmentMatchView
         * @description Where a search query matched inside one segment (FR-10).
         *
         *     Offsets come from the server rather than being recomputed in the browser,
         *     so a highlight cannot disagree with what was actually matched — the two
         *     would otherwise need identical accent-folding in two languages.
         */
        SegmentMatchView: {
            /** Segment Id */
            segment_id: string;
            /** Spans */
            spans: [
                number,
                number
            ][];
        };
        /** SegmentView */
        SegmentView: {
            /** Id */
            id: string;
            /** Participant Id */
            participant_id: string;
            /** Sequence */
            sequence: number;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
            /** Status */
            status: string;
            /** Audio Session Id */
            audio_session_id?: string | null;
        };
        /** TranscriptResponse */
        TranscriptResponse: {
            /** Meeting Id */
            meeting_id: string;
            /** Transcript Version */
            transcript_version: number | null;
            /** Participants */
            participants: components["schemas"]["ParticipantView"][];
            /** Segments */
            segments: components["schemas"]["SegmentView"][];
            /**
             * Audio Sessions
             * @default []
             */
            audio_sessions: components["schemas"]["AudioSessionView"][];
            /** Query */
            query?: string | null;
            /**
             * Total Segments
             * @default 0
             */
            total_segments: number;
            /**
             * Matches
             * @default []
             */
            matches: components["schemas"]["SegmentMatchView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    health_deps_health_deps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_meetings_meetings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_meeting_meetings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMeetingResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_meeting_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailView"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    join_meeting_meetings__meeting_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    end_meeting_meetings__meeting_id__end_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndMeetingResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_transcript_meetings__meeting_id__transcript_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_outputs_meetings__meeting_id__outputs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputsResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_audio_meetings__meeting_id__audio__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
