"""Migration 1: core domain tables.

All eight tables land in one migration. Every tenant-owned table carries
organization_id from the start (ADR-08): cheap now, expensive to retrofit.

Original docstring: migration 1: core domain tables

Revision ID: bc17863d9b4e
Revises:
Create Date: 2026-09-05 19:46:59.661049
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("organization_id", "email", name="uq_users_org_email"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("host_user_id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("source_kind", sa.String(length=24), nullable=False),
        sa.Column("transcript_version", sa.Integer(), nullable=True),
        sa.Column("asr_version", sa.String(length=80), nullable=True),
        sa.Column("transcript_schema_version", sa.Integer(), nullable=False),
        sa.Column("invite_token_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source_kind IN ('direct')", name=op.f("ck_meetings_source_kind_valid")),
        sa.CheckConstraint(
            "state IN ('CREATED', 'JOINABLE', 'LIVE', 'FINALIZING', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_meetings_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["host_user_id"],
            ["users.id"],
            name=op.f("fk_meetings_host_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_meetings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.create_index(
        "ix_meetings_org_created", "meetings", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_meetings_organization_id"), "meetings", ["organization_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("meeting_id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_jobs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_jobs_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency_key"),
    )
    op.create_index("ix_jobs_claimable", "jobs", ["status", "next_run_at"], unique=False)
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_table(
        "meeting_outputs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("meeting_id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("transcript_version", sa.Integer(), nullable=False),
        sa.Column("processor_version", sa.String(length=40), nullable=False),
        sa.Column("llm_model", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("key_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decisions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("action_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("open_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_outputs_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_meeting_outputs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_outputs")),
        sa.UniqueConstraint(
            "meeting_id",
            "transcript_version",
            "processor_version",
            name="uq_outputs_meeting_version_processor",
        ),
    )
    op.create_index(
        op.f("ix_meeting_outputs_organization_id"),
        "meeting_outputs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("meeting_id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=8), nullable=False),
        sa.Column("join_token_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('host', 'guest')", name=op.f("ck_participants_role_valid")),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_participants_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_participants_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_participants_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
    )
    op.create_index("ix_participants_meeting", "participants", ["meeting_id"], unique=False)
    op.create_index(
        op.f("ix_participants_organization_id"), "participants", ["organization_id"], unique=False
    )
    op.create_table(
        "audio_sessions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("meeting_id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("participant_id", sa.String(length=26), nullable=False),
        sa.Column("epoch_ms", sa.BigInteger(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("frames_received", sa.Integer(), nullable=False),
        sa.Column("frames_dropped", sa.Integer(), nullable=False),
        sa.Column("audio_object_key", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_audio_sessions_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audio_sessions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_audio_sessions_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_sessions")),
    )
    op.create_index(
        op.f("ix_audio_sessions_organization_id"),
        "audio_sessions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_audio_sessions_participant", "audio_sessions", ["participant_id"], unique=False
    )
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("meeting_id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("participant_id", sa.String(length=26), nullable=False),
        sa.Column("audio_session_id", sa.String(length=26), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.BigInteger(), nullable=False),
        sa.Column("end_ms", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('final', 'gap')", name=op.f("ck_transcript_segments_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["audio_session_id"],
            ["audio_sessions.id"],
            name=op.f("fk_transcript_segments_audio_session_id_audio_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_transcript_segments_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_transcript_segments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_transcript_segments_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint("participant_id", "sequence", name="uq_segment_participant_sequence"),
    )
    op.create_index(
        "ix_segments_meeting_start", "transcript_segments", ["meeting_id", "start_ms"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_segments_organization_id"),
        "transcript_segments",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcript_segments_organization_id"), table_name="transcript_segments")
    op.drop_index("ix_segments_meeting_start", table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index("ix_audio_sessions_participant", table_name="audio_sessions")
    op.drop_index(op.f("ix_audio_sessions_organization_id"), table_name="audio_sessions")
    op.drop_table("audio_sessions")
    op.drop_index(op.f("ix_participants_organization_id"), table_name="participants")
    op.drop_index("ix_participants_meeting", table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_meeting_outputs_organization_id"), table_name="meeting_outputs")
    op.drop_table("meeting_outputs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_index("ix_jobs_claimable", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_meetings_organization_id"), table_name="meetings")
    op.drop_index("ix_meetings_org_created", table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
